name: Build

on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      NETLIFY_SITE_ID: ${{ vars.NETLIFY_SITE_ID }}
      NETLIFY_TOKEN: ${{ secrets.NETLIFY_TOKEN }}
      BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Deploy preview
        if: github.ref != 'main'
        run: |
          netlify deploy --dir dist --site $NETLIFY_SITE_ID --auth $NETLIFY_TOKEN

      - name: Deploy
        if: github.ref == 'main'
        run: |
          netlify deploy --dir dist --site $NETLIFY_SITE_ID --auth $NETLIFY_TOKEN --prod
